[theme]

# Primary accent for interactive elements
primaryColor = '##024142'

# Background color for the main content area
backgroundColor = '#FDFDFD'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#7FC9BC'

# Color used for almost all text
textColor = '#194041'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
